apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-target-deployment
  namespace: fluid-autoscaler
  labels:
    app: load-target
spec:
  selector:
    matchLabels:
      app: load-target
  template:
    metadata: 
      labels:
        app: load-target
    spec: 
      containers:
      - name: load-target
        image: load-target:0.0.4-ubuntu
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: load-target
  namespace: fluid-autoscaler
  labels:
    app: load-target
spec:
  type: ClusterIP
  selector:
    app: load-target
  ports:
    - name: http
      port: 80          # The port the Service listens on inside the cluster.
      targetPort: 8080  # The port the container actually serves on.
