apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: fluid-autoscaler
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: fluid-autoscaler
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:8.8-trixie
        ports:
        - containerPort: 6379
          name: tcp-redis
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi
        volumeMounts:
        - name: redis-data
          mountPath: /data

      - name: redis-exporter # sidecar to export redis metrics
        image: oliver006/redis_exporter:v1.62.0
        env:
        - name: REDIS_ADDR
          value: "redis://localhost:6379"
        - name: REDIS_EXPORTER_CHECK_SINGLE_KEYS
          value: "jobs"
        ports:
        - containerPort: 9121
          name: redis-metrics
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            memory: 64Mi
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fluid-autoscaler
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
    - name: redis-metrics
      port: 9121
      targetPort: redis-metrics
