apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: fluid-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers: # add sidecar container for monitoring queue depth?
      - name: redis
        image: redis:8.8-trixie
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fluid-autoscaler
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
