apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: fluid-autoscaler
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers: # add sidecar container for monitoring queue depth?
      - name: redis
        image: redis:8.8-trixie
        ports:
        - containerPort: 6389
---
apiVersion: v1
kind: Service
metadata:
  name: redis-clusterip
  namespace: fluid-autoscaler
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: http
      port: 6379
      targetPort: 6379
