apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-target-service-monitor
  namespace: monitoring
  labels:
    release: prom-monitoring
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - fluid-autoscaler
  selector:
    matchLabels:
      app: "load-target"
