apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fluid-autoscaler
  labels:
    app: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
    - name: redis-metrics
      port: 9121
      targetPort: redis-metrics
